In [34]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df=pd.read_csv('/content/USArrests.csv')

In [35]:
df.head()

   Murder  Assault  UrbanPop  Rape       State
0    13.2      236        58  21.2     Alabama
1    10.0      263        48  44.5      Alaska
2     8.1      294        80  31.0     Arizona
3     8.8      190        50  19.5    Arkansas
4     9.0      276        91  40.6  California

In [36]:
df.sample(3)

    Murder  Assault  UrbanPop  Rape         State
4      9.0      276        91  40.6    California
12    10.4      249        83  24.0      Illinois
37     6.3      106        72  14.9  Pennsylvania

In [37]:
df[df['Murder']>df['Assault']]

Empty DataFrame
Columns: [Murder, Assault, UrbanPop, Rape, State]
Index: []

In [39]:
df.mean(numeric_only=True)

Murder        7.788
Assault     170.760
UrbanPop     65.540
Rape         21.232
dtype: float64

In [40]:
df.sum()

Murder                                                  389.4
Assault                                                  8538
UrbanPop                                                 3277
Rape                                                   1061.6
State       AlabamaAlaskaArizonaArkansasCaliforniaColorado...
dtype: object

In [41]:
df.min()

Murder          0.8
Assault          45
UrbanPop         32
Rape            7.3
State       Alabama
dtype: object

In [43]:
df.std(numeric_only=True)

Murder       4.355510
Assault     83.337661
UrbanPop    14.474763
Rape         9.366385
dtype: float64