In [26]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df=pd.read_csv('/content/USSeatBelts.csv')

In [27]:
df.tail()

,rownames,state,year,miles,fatalities,seatbelt,speed65,speed70,drinkage,alcohol,income,age,enforce
760,761,WY,1993,6770,0.017725,0.67,yes,no,yes,no,19535,34.214382,secondary
761,762,WY,1994,6689,0.021528,0.70,yes,no,yes,no,19865,34.455780,secondary
762,763,WY,1995,7044,0.024134,0.71,yes,yes,yes,no,20685,34.766613,secondary
763,764,WY,1996,7360,0.019429,0.72,yes,yes,yes,no,21524,35.074348,secondary
764,765,WY,1997,7576,0.018083,0.75,yes,yes,yes,no,22596,35.386463,secondary

In [28]:
df.head()

,rownames,state,year,miles,fatalities,seatbelt,speed65,speed70,drinkage,alcohol,income,age,enforce
0,1,AK,1983,3358,0.044669,NaN,no,no,yes,no,17973,28.234966,no
1,2,AK,1984,3589,0.037336,NaN,no,no,yes,no,18093,28.343542,no
2,3,AK,1985,3840,0.033073,NaN,no,no,yes,no,18925,28.372816,no
3,4,AK,1986,4008,0.025200,NaN,no,no,yes,no,18466,28.396652,no
4,5,AK,1987,3900,0.019487,NaN,no,no,yes,no,18021,28.453251,no

In [29]:
df.sort_values(by='year',ascending=False)

,rownames,state,year,miles,fatalities,seatbelt,speed65,speed70,drinkage,alcohol,income,age,enforce
764,765,WY,1997,7576,0.018083,0.7500,yes,yes,yes,no,22596,35.386463,secondary
419,420,NC,1997,81893,0.018109,0.8500,yes,no,yes,yes,23168,36.275143,primary
404,405,MT,1997,9392,0.028216,0.7255,yes,no,yes,no,19660,36.829769,secondary
59,60,AZ,1997,43491,0.021867,0.6300,yes,yes,yes,no,21998,35.700436,secondary
359,360,MN,1997,48350,0.012410,0.6500,yes,no,yes,no,26243,35.776623,secondary
...,...,...,...,...,...,...,...,...,...,...,...,...,...
420,421,ND,1983,5363,0.021630,NaN,no,no,yes,no,11100,33.747570,no
735,736,WV,1983,11696,0.036337,NaN,no,no,no,no,9417,35.215950,no
750,751,WY,1983,5059,0.034196,NaN,no,no,no,no,12352,31.140636,no
15,16,AL,1983,31032,0.029969,NaN,no,no,no,no,9505,34.200645,no
0,1,AK,1983,3358,0.044669,NaN,no,no,yes,no,17973,28.234966,no

In [30]:
df[['year']]

     year
0    1983
1    1984
2    1985
3    1986
4    1987
..    ...
760  1993
761  1994
762  1995
763  1996
764  1997

[765 rows x 1 columns]

In [31]:
df.describe()

,rownames,year,miles,fatalities,seatbelt,income,age
count,765.000000,765.00000,765.000000,765.000000,556.000000,765.000000,765.000000
mean,383.000000,1990.00000,41447.734641,0.021490,0.528852,17992.586928,35.137194
std,220.980768,4.32332,43961.990037,0.006171,0.170186,4811.459296,1.698131
min,1.000000,1983.00000,3099.000000,0.008327,0.060000,8372.000000,28.234966
25%,192.000000,1986.00000,11401.000000,0.017341,0.420000,14266.000000,34.387501
50%,383.000000,1990.00000,30319.000000,0.021199,0.550000,17624.000000,35.391766
75%,574.000000,1994.00000,52312.000000,0.024774,0.650000,21080.000000,36.130787
max,765.000000,1997.00000,285612.000000,0.045470,0.870000,35863.000000,39.169582

In [32]:
df.dtypes

rownames        int64
state          object
year            int64
miles           int64
fatalities    float64
seatbelt      float64
speed65        object
speed70        object
drinkage       object
alcohol        object
income          int64
age           float64
enforce        object
dtype: object

In [33]:
df.nunique()

rownames      765
state          51
year           15
miles         758
fatalities    765
seatbelt      245
speed65         2
speed70         2
drinkage        2
alcohol         2
income        750
age           764
enforce         3
dtype: int64