In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df=pd.read_csv('/VerbAgg.csv')

In [13]:
df.sample(4)

,img,title,console,genre,publisher,developer,critic_score,total_sales,na_sales,jp_sales,pal_sales,other_sales,release_date,last_update
87,/games/boxart/full_1882754JapanFrontccc.jpg,Final Fantasy XV,PS4,Role-Playing,Square Enix,Square Enix,8.1,5.07,1.81,1.05,1.53,0.68,2016-11-29,2018-05-04
38419,/games/boxart/full_5716095AmericaFrontccc.jpg,The Hula Hamsters,PC,Misc,3A Studios,3A Studios Inc,NaN,NaN,NaN,NaN,NaN,NaN,2005-01-01,NaN
34355,/games/boxart/full_9747592JapanFrontccc.jpg,Family Mahjong II: Shanghai he no Michi,NES,Misc,Namco,Nihon Bussan,NaN,NaN,NaN,NaN,NaN,NaN,1988-11-25,NaN
34270,/games/boxart/default.jpg,Escape Trick: Ninja Castle,DSi,Misc,Intense,Unknown,NaN,NaN,NaN,NaN,NaN,NaN,2011-09-22,NaN

In [23]:
df.columns

Index(['img', 'Title', 'console', 'genre', 'publisher', 'developer',
       'critic_score', 'total_sales', 'na_sales', 'jp_sales', 'pal_sales',
       'other_sales', 'release_date', 'last_update'],
      dtype='object')

In [19]:
df.rename(columns={'title':'Heading'},inplace=True)

In [20]:
df.head()

,img,Title,console,genre,publisher,developer,critic_score,total_sales,na_sales,jp_sales,pal_sales,other_sales,release_date,last_update
0,/games/boxart/full_6510540AmericaFrontccc.jpg,Grand Theft Auto V,PS3,Action,Rockstar Games,Rockstar North,9.4,20.32,6.37,0.99,9.85,3.12,2013-09-17,NaN
1,/games/boxart/full_5563178AmericaFrontccc.jpg,Grand Theft Auto V,PS4,Action,Rockstar Games,Rockstar North,9.7,19.39,6.06,0.60,9.71,3.02,2014-11-18,2018-01-03
2,/games/boxart/827563ccc.jpg,Grand Theft Auto: Vice City,PS2,Action,Rockstar Games,Rockstar North,9.6,16.15,8.41,0.47,5.49,1.78,2002-10-28,NaN
3,/games/boxart/full_9218923AmericaFrontccc.jpg,Grand Theft Auto V,X360,Action,Rockstar Games,Rockstar North,NaN,15.86,9.06,0.06,5.33,1.42,2013-09-17,NaN
4,/games/boxart/full_4990510AmericaFrontccc.jpg,Call of Duty: Black Ops 3,PS4,Shooter,Activision,Treyarch,8.1,15.09,6.18,0.41,6.05,2.44,2015-11-06,2018-01-14

In [22]:
df['Title'].value_counts()

Title
Plants vs. Zombies                                            17
Pac-Man                                                       16
Monopoly                                                      15
Doom                                                          14
Double Dragon                                                 14
                                                              ..
Tlicolity Eyes: Twinkle Snowtime                               1
The Mind's Eclipse                                             1
The House in Fata Morgana: Dreams of the Revenants Edition     1
The House in Fata Morgana: Dream of the Revenants Edition      1
The Fox Is Waiting For Me                                      1
Name: count, Length: 39798, dtype: int64

In [24]:
df.shape

(64016, 14)

In [25]:
df.isnull().sum()

img                 0
Title               0
console             0
genre               0
publisher           0
developer          17
critic_score    57338
total_sales     45094
na_sales        51379
jp_sales        57290
pal_sales       51192
other_sales     48888
release_date     7051
last_update     46137
dtype: int64