In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df=pd.read_excel('/WorldBank.xlsx')

In [2]:
df.head()

,Country Name,Country Code,Region,IncomeGroup,Year,"Birth rate, crude (per 1,000 people)","Death rate, crude (per 1,000 people)",Electric power consumption (kWh per capita),GDP (USD),GDP per capita (USD),Individuals using the Internet (% of population),"Infant mortality rate (per 1,000 live births)",Life expectancy at birth (years),Population density (people per sq. km of land area),Unemployment (% of total labor force) (modeled ILO estimate)
0,Afghanistan,AFG,South Asia,Low income,2018,NaN,NaN,NaN,1.936300e+10,520.897,NaN,47.9,NaN,56.9378,1.542
1,Afghanistan,AFG,South Asia,Low income,2017,33.211,6.575,NaN,2.019180e+10,556.302,13.50,49.5,64.130,55.5960,1.559
2,Afghanistan,AFG,South Asia,Low income,2016,33.981,6.742,NaN,1.936260e+10,547.228,11.20,51.2,63.763,54.1971,1.634
3,Afghanistan,AFG,South Asia,Low income,2015,34.809,6.929,NaN,1.990710e+10,578.466,8.26,53.1,63.377,52.7121,1.679
4,Afghanistan,AFG,South Asia,Low income,2014,35.706,7.141,NaN,2.048490e+10,613.856,7.00,55.1,62.966,51.1148,1.735

In [3]:
df.tail()

,Country Name,Country Code,Region,IncomeGroup,Year,"Birth rate, crude (per 1,000 people)","Death rate, crude (per 1,000 people)",Electric power consumption (kWh per capita),GDP (USD),GDP per capita (USD),Individuals using the Internet (% of population),"Infant mortality rate (per 1,000 live births)",Life expectancy at birth (years),Population density (people per sq. km of land area),Unemployment (% of total labor force) (modeled ILO estimate)
12444,Zimbabwe,ZWE,Sub-Saharan Africa,Low income,1964,47.770,13.083,NaN,1.217138e+09,281.558,NaN,83.2,54.849,11.1745,NaN
12445,Zimbabwe,ZWE,Sub-Saharan Africa,Low income,1963,47.876,13.419,NaN,1.159512e+09,277.480,NaN,85.7,54.403,10.8019,NaN
12446,Zimbabwe,ZWE,Sub-Saharan Africa,Low income,1962,47.950,13.762,NaN,1.117602e+09,276.689,NaN,88.1,53.946,10.4413,NaN
12447,Zimbabwe,ZWE,Sub-Saharan Africa,Low income,1961,47.988,14.104,NaN,1.096647e+09,280.829,NaN,90.5,53.483,10.0944,NaN
12448,Zimbabwe,ZWE,Sub-Saharan Africa,Low income,1960,47.996,14.441,NaN,1.052990e+09,278.814,NaN,92.8,53.019,NaN,NaN

In [4]:
df.describe()

,Year,"Birth rate, crude (per 1,000 people)","Death rate, crude (per 1,000 people)",Electric power consumption (kWh per capita),GDP (USD),GDP per capita (USD),Individuals using the Internet (% of population),"Infant mortality rate (per 1,000 live births)",Life expectancy at birth (years),Population density (people per sq. km of land area),Unemployment (% of total labor force) (modeled ILO estimate)
count,12449.00000,11440.000000,11416.000000,5848.000000,9.578000e+03,9575.000000,5064.000000,9984.000000,11176.000000,11845.000000,5208.000000
mean,1989.00000,28.643276,10.588539,3175.294686,1.700740e+11,8231.812259,23.334471,51.704437,64.044692,318.861370,8.295079
std,17.03007,13.131893,5.489382,4467.139298,8.979866e+11,16173.539954,28.319388,46.131039,11.491087,1593.406041,6.290703
min,1960.00000,6.900000,1.127000,0.000000,8.824450e+06,34.790600,0.000000,1.400000,18.907000,0.098625,0.140000
25%,1974.00000,16.600000,6.863750,390.385750,1.393010e+09,513.145500,0.594949,14.475000,55.917750,19.783400,3.687000
50%,1989.00000,27.545500,9.200000,1541.895000,7.275305e+09,1852.810000,8.406225,37.000000,67.276000,64.007500,6.775000
75%,2004.00000,40.881250,12.687000,4313.767500,4.857782e+10,7774.565000,41.295950,78.200000,72.692250,144.823000,11.212250
max,2018.00000,58.227000,54.444000,54799.200000,2.050000e+13,189171.000000,100.000000,279.400000,85.417100,21389.100000,37.940000

In [5]:
df.isnull().sum()

Country Name                                                       0
Country Code                                                       0
Region                                                             0
IncomeGroup                                                        0
Year                                                               0
Birth rate, crude (per 1,000 people)                            1009
Death rate, crude (per 1,000 people)                            1033
Electric power consumption (kWh per capita)                     6601
GDP (USD)                                                       2871
GDP per capita (USD)                                            2874
Individuals using the Internet (% of population)                7385
Infant mortality rate (per 1,000 live births)                   2465
Life expectancy at birth (years)                                1273
Population density (people per sq. km of land area)              604
Unemployment (% of total labor force) (modeled ILO estimate)    7241
dtype: int64

In [7]:
df.shape

(12449, 15)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12449 entries, 0 to 12448
Data columns (total 15 columns):
 #   Column                                                        Non-Null Count  Dtype
---  ------                                                        --------------  -----
 0   Country Name                                                  12449 non-null  object
 1   Country Code                                                  12449 non-null  object
 2   Region                                                        12449 non-null  object
 3   IncomeGroup                                                   12449 non-null  object
 4   Year                                                          12449 non-null  int64
 5   Birth rate, crude (per 1,000 people)                          11440 non-null  float64
 6   Death rate, crude (per 1,000 people)                          11416 non-null  float64
 7   Electric power consumption (kWh per capita)                   5848 non-null   float64
 8   GDP (USD)                                                     9578 non-null   float64
 9   GDP per capita (USD)                                          9575 non-null   float64
 10  Individuals using the Internet (% of population)              5064 non-null   float64
 11  Infant mortality rate (per 1,000 live births)                 9984 non-null   float64
 12  Life expectancy at birth (years)                              11176 non-null  float64
 13  Population density (people per sq. km of land area)           11845 non-null  float64
 14  Unemployment (% of total labor force) (modeled ILO estimate)  5208 non-null   float64
dtypes: float64(10), int64(1), object(4)
memory usage: 1.4+ MB

In [10]:
df.dtypes

Country Name                                                     object
Country Code                                                     object
Region                                                           object
IncomeGroup                                                      object
Year                                                              int64
Birth rate, crude (per 1,000 people)                            float64
Death rate, crude (per 1,000 people)                            float64
Electric power consumption (kWh per capita)                     float64
GDP (USD)                                                       float64
GDP per capita (USD)                                            float64
Individuals using the Internet (% of population)                float64
Infant mortality rate (per 1,000 live births)                   float64
Life expectancy at birth (years)                                float64
Population density (people per sq. km of land area)             float64
Unemployment (% of total labor force) (modeled ILO estimate)    float64
dtype: object

In [11]:
df.dropna()

,Country Name,Country Code,Region,IncomeGroup,Year,"Birth rate, crude (per 1,000 people)","Death rate, crude (per 1,000 people)",Electric power consumption (kWh per capita),GDP (USD),GDP per capita (USD),Individuals using the Internet (% of population),"Infant mortality rate (per 1,000 live births)",Life expectancy at birth (years),Population density (people per sq. km of land area),Unemployment (% of total labor force) (modeled ILO estimate)
63,Albania,ALB,Europe & Central Asia,Upper middle income,2014,12.259,7.219,2309.370,1.322820e+10,4578.670,60.100000,8.9,77.813,105.4420,17.490
64,Albania,ALB,Europe & Central Asia,Upper middle income,2013,12.257,7.096,2533.250,1.277630e+10,4413.080,57.200000,9.5,77.554,105.6600,15.866
65,Albania,ALB,Europe & Central Asia,Upper middle income,2012,12.197,6.996,2118.330,1.231980e+10,4247.610,54.656000,10.2,77.252,105.8540,13.376
66,Albania,ALB,Europe & Central Asia,Upper middle income,2011,12.100,6.915,2205.700,1.289090e+10,4437.180,49.000000,11.0,76.914,106.0290,13.481
67,Albania,ALB,Europe & Central Asia,Upper middle income,2010,12.001,6.841,1943.340,1.192700e+10,4094.360,45.000000,11.9,76.562,106.3150,14.086
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12410,Zimbabwe,ZWE,Sub-Saharan Africa,Low income,1998,31.770,15.197,876.303,6.401970e+09,544.984,0.081648,59.9,46.466,30.3660,6.374
12411,Zimbabwe,ZWE,Sub-Saharan Africa,Low income,1997,31.926,14.403,901.380,8.529570e+09,731.948,0.033080,60.4,47.661,30.1234,6.930
12412,Zimbabwe,ZWE,Sub-Saharan Africa,Low income,1996,32.185,13.563,867.326,8.553150e+09,741.096,0.016790,60.4,49.009,29.8338,6.271
12413,Zimbabwe,ZWE,Sub-Saharan Africa,Low income,1995,32.560,12.707,822.998,7.111270e+09,623.210,0.007684,59.5,50.480,29.4965,5.588
12414,Zimbabwe,ZWE,Sub-Saharan Africa,Low income,1994,33.067,11.861,777.588,6.890680e+09,611.866,0.001739,57.7,52.044,29.1114,4.960